server:
 port: 8580

spring:
 application:
    name: customer-service
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/bank
    username: root
 jpa:
    show-sql: true
    hibernate:
      ddl-auto: create